# Generated by Django 4.2.5 on 2023-09-25 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BMSAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bms_api_url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CsvOrExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=100)),
                ('upload_file', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('mech_nat_vent_infiltration', models.DecimalField(decimal_places=5, max_digits=8)),
                ('external_infiltration', models.DecimalField(decimal_places=5, max_digits=8)),
                ('task_lighting', models.DecimalField(decimal_places=5, max_digits=8)),
                ('general_lighting', models.DecimalField(decimal_places=5, max_digits=8)),
                ('miscellaneous', models.DecimalField(decimal_places=5, max_digits=8)),
                ('process', models.DecimalField(decimal_places=5, max_digits=8)),
                ('computer_equip', models.DecimalField(decimal_places=5, max_digits=8)),
                ('occupancy', models.DecimalField(decimal_places=5, max_digits=8)),
                ('solar_gains', models.DecimalField(decimal_places=5, max_digits=8)),
                ('zone_sensible_cooling', models.DecimalField(decimal_places=5, max_digits=8)),
                ('air_temperature', models.DecimalField(decimal_places=5, max_digits=8)),
                ('radiant_temperature', models.DecimalField(decimal_places=5, max_digits=8)),
                ('operative_temperature', models.DecimalField(decimal_places=5, max_digits=8)),
                ('room_electricity', models.DecimalField(decimal_places=5, max_digits=8)),
                ('lighting', models.DecimalField(decimal_places=5, max_digits=8)),
                ('system_fans', models.DecimalField(decimal_places=5, max_digits=8)),
                ('system_pumps', models.DecimalField(decimal_places=5, max_digits=8)),
                ('cooling_electricity', models.DecimalField(decimal_places=5, max_digits=8)),
                ('exterior_lighting', models.DecimalField(decimal_places=5, max_digits=8)),
                ('outside_dry_bulb_temperature', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
    ]
