# Generated by Django 4.2.5 on 2023-09-26 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('mech_nat_vent_infiltration', models.DecimalField(decimal_places=5, max_digits=8)),
                ('external_infiltration', models.DecimalField(decimal_places=5, max_digits=8)),
                ('task_lighting', models.DecimalField(decimal_places=5, max_digits=8)),
                ('general_lighting', models.DecimalField(decimal_places=5, max_digits=8)),
                ('miscellaneous', models.DecimalField(decimal_places=5, max_digits=8)),
                ('process', models.DecimalField(decimal_places=5, max_digits=8)),
                ('computer_equip', models.DecimalField(decimal_places=5, max_digits=8)),
                ('occupancy', models.DecimalField(decimal_places=5, max_digits=8)),
                ('solar_gains', models.DecimalField(decimal_places=5, max_digits=8)),
                ('zone_sensible_cooling', models.DecimalField(decimal_places=5, max_digits=8)),
                ('air_temperature', models.DecimalField(decimal_places=5, max_digits=8)),
                ('radiant_temperature', models.DecimalField(decimal_places=5, max_digits=8)),
                ('operative_temperature', models.DecimalField(decimal_places=5, max_digits=8)),
                ('room_electricity', models.DecimalField(decimal_places=5, max_digits=8)),
                ('lighting', models.DecimalField(decimal_places=5, max_digits=8)),
                ('system_fans', models.DecimalField(decimal_places=5, max_digits=8)),
                ('system_pumps', models.DecimalField(decimal_places=5, max_digits=8)),
                ('cooling_electricity', models.DecimalField(decimal_places=5, max_digits=8)),
                ('exterior_lighting', models.DecimalField(decimal_places=5, max_digits=8)),
                ('outside_dry_bulb_temperature', models.DecimalField(decimal_places=5, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='CsvOrExcelUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=100)),
                ('upload_file', models.FileField(upload_to='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BMSSENSOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('energy_level', models.FloatField()),
                ('temperature', models.FloatField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
