# Generated by Django 4.2.5 on 2023-09-23 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('veraai', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnergyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('mech_nat_vent_infiltration', models.FloatField()),
                ('external_infiltration', models.FloatField()),
                ('task_lighting', models.FloatField()),
                ('general_lighting', models.FloatField()),
                ('miscellaneous', models.FloatField()),
                ('process', models.FloatField()),
                ('computer_equip', models.FloatField()),
                ('occupancy', models.FloatField()),
                ('solar_gains', models.FloatField()),
                ('zone_sensible_cooling', models.FloatField()),
                ('air_temperature', models.FloatField()),
                ('radiant_temperature', models.FloatField()),
                ('operative_temperature', models.FloatField()),
                ('room_electricity', models.FloatField()),
                ('lighting', models.FloatField()),
                ('system_fans', models.FloatField()),
                ('system_pumps', models.FloatField()),
                ('cooling_electricity', models.FloatField()),
                ('exterior_lighting', models.FloatField()),
                ('outside_dry_bulb_temperature', models.FloatField()),
            ],
        ),
    ]
